### ISSUE TITLE
The long and winding road to 8.13

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#2790]
Aim for a release in late May.

## TODO

- [x] dzsave to target
- [x] tiffsave to target see PR #2798 
- [x] GIF save improvements see PR #2797
- [x] support linear light in JXL see PR #2815
- [x] resolve JXL lossless encode issues
- [x] update downstream projects where necessary
- [x] fix JXL save of float RGB (need new SAVEABLE enum)
- [x] another round of GIF fixes
- [x] website docs update
- [x] release notes and a news post to write
- [x] put out an rc for evaluation
- [x] .... and get the rc at least mostly approved by downstream users
- [ ] publicity

Milestone: https://github.com/libvips/libvips/milestone/11

**Comment by jcupitt** [comment]
@dloebl we should get some GIF fixes in too. Please add some notes to the TODO above if you like.

**Comment by vansante** [comment]
Would love to see [this one](https://github.com/libvips/libvips/issues/2668) :wink:

**Comment by jcupitt** [comment]
pyvips now has support in master for the new targetcustom stuff

**Comment by kleisauke** [comment]
I just emailed Remi Collet with a patch that migrates the vips spec file to build with Meson for the upcoming 8.13 release. While doing so, I noticed 2 things:
- The `VIPS_VERSION_STRING` definition doesn't include the ChangeLog date when building with Meson, but perhaps that's OK.
https://github.com/libvips/libvips/blob/111eef0049068bd12e0ab5ffa1e26246f90a0a5f/libvips/include/vips/meson.build#L132
https://github.com/libvips/libvips/blob/111eef0049068bd12e0ab5ffa1e26246f90a0a5f/configure.ac#L29
- nifticlib usage needs to be disabled on Fedora due to missing pkg-config files. This will hopefully be fixed once PR https://github.com/NIFTI-Imaging/nifti_clib/pull/140 is merged.

**Comment by jcupitt** [comment]
OK, I think we're almost ready. Shall we feature-freeze and do a release?

**Comment by kleisauke** [comment]
I have nothing to add for 8.13, so I'm fine with a feature freeze and a possible release candidate. Though, I noticed some pending cgifsave PRs for possible inclusion.

**Comment by jcupitt** [comment]
I think I found another cgifsave issue --- this  GIF:

![sample](https://user-images.githubusercontent.com/580843/171033026-2c46be03-117e-4aad-b8be-33faf75ce806.gif)

When copied like this:

```
vips copy sample.gif[n=-1] x.gif
```

Becomes this:

![x](https://user-images.githubusercontent.com/580843/171033130-aa18e9db-4a6d-4dd4-9e59-f498979fb715.gif)

I think the problem is that the colour table is being improved by the render pass. It's improving the colour table based on the first frame and that of course makes it much worse for the later frames.

We probably need to remove the improve ctable feature in global cmap mode.

**Comment by dloebl** [comment]
Interesting find. This looks similar to the issue mentioned here: https://github.com/libvips/libvips/pull/2797#issuecomment-1126034282
We probably want to get the palette right after quantizing the attached global colour table then - so it does not get "optimized" during dithering/remapping?
https://github.com/libvips/libvips/blob/6260a37136973f3d231d0e2c28af6190126c664e/libvips/foreign/cgifsave.c#L629

**Comment by jcupitt** [comment]
OK, the palette improvement issue is done. I've started writing a "what's new" post -- any comments?

https://github.com/libvips/libvips/blob/gh-pages-8.13/_posts/2022-05-28-What's-new-in-8.13.md

- @kleisauke would you like to expand the image quality section?
- @dloebl @DarthSim would you like to add to the GIF section?
- does the running order look OK? maybe the new build system should not be first? only devs would care about that

**Comment by DarthSim** [comment]
I don't think we should remove `interframe-maxerror` and `interpalette-maxerror`. While their default values are pretty good, some may want to tune them for their case.

**Comment by jcupitt** [comment]
Release candidate 1: https://github.com/libvips/libvips/releases/tag/v8.13.0-rc1

Release notes posted: https://www.libvips.org/2022/05/28/What's-new-in-8.13.html

**Comment by jcupitt** [comment]
... let's wait a week for people to test rc1, and if no one finds anything too bad, we'll announce 8.13.0 on 26 June.

**Comment by Elad-Laufer** [comment]
When building from source in a container (with lima) I get the following error:

```
#6 100.3 Found runner: ['/usr/bin/ninja']
#6 100.6 ninja: Entering directory `/tmp/libvips-8.13.0-rc1/libvips-release'
#6 100.6 ninja: no work to do.
#6 111.2 3/8 seq         OK             3.48s
#6 111.2 4/8 stall       OK             2.18s
#6 111.2 5/8 threading   OK             7.94s
#6 111.2 7/8 descriptors OK             0.47s
#6 111.2 8/8 fuzz        OK             4.73s
#6 111.2 
#6 111.2 Summary of Failures:
#6 111.2 
#6 111.2 1/8 cli         FAIL           0.42s (exit status 1)
#6 111.2 2/8 formats     FAIL           0.37s (exit status 1)
#6 111.2 6/8 connections FAIL           0.37s (exit status 1)
#6 111.2 
#6 111.2 Ok:                 5   
#6 111.2 Expected Fail:      0   
#6 111.2 Fail:               3   
#6 111.2 Unexpected Pass:    0   
#6 111.2 Skipped:            0   
#6 111.2 Timeout:            0   
```

The Dockerfile:

```
FROM golang:bullseye as builder

ARG LIBVIPS_VERSION="8.13.0-rc1"

# Installs libvips + required libraries

RUN DEBIAN_FRONTEND=noninteractive \
    apt update && \
    apt install --no-install-recommends -y \
    meson cmake ca-certificates \
    libtool autotools-dev build-essential curl \
    libgirepository1.0-dev gtk-doc-tools libglib2.0-dev \
    libjpeg62-turbo-dev libpng-dev \
    libwebp-dev libtiff5-dev libgif-dev libexif-dev libxml2-dev libpoppler-glib-dev \
    swig libmagickwand-dev libpango1.0-dev libmatio-dev libopenslide-dev libcfitsio-dev \
    libgsf-1-dev libfftw3-dev liborc-0.4-dev librsvg2-dev libimagequant-dev libheif-dev \
    libopenjp2-7-dev liblcms2-dev

RUN cd /tmp && \
    curl -fsSLO https://github.com/libvips/libvips/archive/refs/tags/v${LIBVIPS_VERSION}.tar.gz && \
    tar zvxf v${LIBVIPS_VERSION}.tar.gz && \
    cd libvips-${LIBVIPS_VERSION} && \
    meson setup libvips-release --prefix=/tmp --libdir=lib --buildtype=release && \
    cd libvips-release && \
    meson compile && \
    meson test && \
    meson install && \
    ldconfig
```

**Comment by Elad-Laufer** [comment]
Solved the Debian build issue by installing 'bc':

```
RUN DEBIAN_FRONTEND=noninteractive \
    apt update && \
    apt install --no-install-recommends -y \
    meson cmake ca-certificates \
```

thanks @netanel-r

**Comment by jcupitt** [comment]
Here's `rc2`.:

https://github.com/libvips/libvips/releases/tag/v8.13.0-rc2

Let's aim for release on Sunday 17 July (assuming nothing too bad happens in testing).

**Comment by danielniccoli** [comment]
Any chance for a Windows release?  The last Windows binary 8.12.1 still has a bug impacting me, that was fixed in 8.12.2. 🙏

**Comment by jcupitt** [comment]
Kleis has made 8.12.2 binaries here:

https://github.com/libvips/build-win64-mxe/releases/tag/v8.12.2

And 8.13.0-rc2 here:

https://github.com/libvips/build-win64-mxe/releases/tag/v8.13.0-rc2

**Comment by jcupitt** [comment]
Ooof right, sorry, I was on holiday and had less time than I expected. Now I'm back!

A few more bugfixes have gone in this week, but only a few. Shall we do 8.13.0 now? Any thoughts?

**Comment by kleisauke** [comment]
Nothing extra from me for 8.13, so feel to :shipit: whenever you're ready.

**Comment by jcupitt** [comment]
Woo hoo! Well done us!

https://github.com/libvips/libvips/releases/tag/v8.13.0

**Comment by jcupitt** [comment]
Just publicity left to do now. Please feel feel free to tweet, post on reddit, whatever you like.
