### ISSUE TITLE
The road to 8.14

### ISSUE THREAD

**Issue by jcupitt** [libvips/libvips#3240]
We have 8.14.0-rc1 now, including win32 binaries:

https://github.com/libvips/libvips/releases/tag/v8.14.0-rc1

Website updated in this branch:

https://github.com/libvips/libvips/tree/gh-pages-8.14

Draft release notes here:

https://github.com/libvips/libvips/blob/gh-pages-8.14/_posts/2022-12-22-What's-new-in-8.14.md

## TODO

- [x] there have been some minor doc fixes since rc1, we need to regen the C++ binding 
- [x] and the website docs
- [x] test downstream bindings ... pyvips and ruby-vips seem fine
- [x] test sharp
- [x] benchmark
- [ ] test packaging for deb and rpm now that auto* has gone

**Comment by lovell** [comment]
The sharp tests are passing on all platforms/archs using 8.14.0-rc1 :tada: 

https://github.com/lovell/sharp/actions/runs/3801639451
https://github.com/lovell/sharp/actions/runs/3801639453
https://app.circleci.com/pipelines/github/lovell/sharp/329/workflows/1a6aecda-f7c4-4de4-8820-8ef609f11f62

**Comment by kleisauke** [comment]
The NetVips tests are also passing on all platforms/archs using 8.14.0-rc1. :heavy_check_mark: 
https://www.nuget.org/packages/NetVips.Native/8.14.0-rc1
https://github.com/kleisauke/net-vips/actions/runs/3806284622
https://github.com/kleisauke/net-vips/runs/10362832354
https://ci.appveyor.com/project/kleisauke/net-vips/builds/45802136

The wasm-vips test suite passes locally using 8.14.0-rc1 (on the [`vips-8.14`](https://github.com/kleisauke/wasm-vips/tree/vips-8.14) branch). :heavy_check_mark: 

I deployed an A/B test on the [`weserv/images`](https://github.com/weserv/images) project using 8.14.0-rc1, which I'll be monitoring for a few days. :mag:

**Comment by jcupitt** [comment]
That's great! Let's make 14.0!

I shouldn't, but I'd like to squeeze that `arrayjoin` improvement in -- it really has a huge effect on performance (runtime goes from 2m to 1s on that benchmark). I'll try to finish testing that today.

**Comment by kleisauke** [comment]
FWIW, I'll do some soak related threading tests today. I noticed that the revised threadpool system is allowed to use `$(nproc) + 2` threads (`pool->max_workers`) per image processing pipeline. As far as I know, the previous GLib threadpool limits the number of threads per process instead.

**Comment by kleisauke** [comment]
... I should clarify my previous comment with a graph.
[![graph](https://kleisauke.nl/threads-pinpoint-1672290435-1672398435.png)](https://kleisauke.nl/threads-pinpoint-1672290435-1672398435.png)

So, libvips 8.14.0-rc1 was yesterday deployed on a server with 6 cores (around 13:15 in UTC+1) and I noticed an immediate increase in the number of threads (those two "dips" are caused by [`SIGHUP`-ing the nginx master process](https://nginx.org/en/docs/control.html)).

Perhaps this is fine(?), I was just a bit worried how this behavior would be on a server with 12 cores.

/cc @andrieslouw

**Comment by jcupitt** [comment]
Ah OK hmm, I'm not sure either. I'll hold off the release.

**Comment by jcupitt** [comment]
To make a concrete example: suppose you have a machine with 12 hardware threads and you try to run two pipelines at once, each of which can saturate all cores. 8.14 will start (approximately) 24 threads and leave it to the OS to decide how to allocate the available cores to the workload.

I think this is probably the correct behaviour. The OS has a lot more information about threads, affinity, and how hardware threads releate to cores. It can probably do a better job than libvips could, and linux at least is fine with many 1000s of threads in a process.

Perhaps the danger is that the libvips process might be more likely to starve other important processes on the machine, such as the nginx server? Though I'd expect the OS scheduler to prevent that.

**Comment by jcupitt** [comment]
I had everything ready to go, so rather than lose the work, I made 8.14.0 but left it tagged as a prerelese https://github.com/libvips/libvips/releases/tag/v8.14.0

We can remove the prerelease tag if we decide to go ahead.

**Comment by kleisauke** [comment]
No problem! A screenshot is worth a thousand words:
https://kleisauke.nl/Screenshot%20from%202022-12-30%2014-39-19.png

So, only `$(nproc) + 2` threads are actually busy, which means this is probably because idle threads are no longer stopped after a regular timeout (which would help in long-running processes). Previously, the GLib threadpool did this after 15 seconds. I'm working on a similar patch for the revised threadpool system, sorry for not having caught this earlier.

Note that I didn't found any issues with the soak tests in:
https://gist.github.com/kleisauke/fbc5a8bb418da2f660c06bdd07115e10
https://gist.github.com/jcupitt/3656815cf203a43611fdb1361a252672

So, feel free to remove the pre-release tag.

**Comment by jcupitt** [comment]
I could make a quick PR for a threadpool scavenger, I think it would be fairly easy. Or have you made one already?

**Comment by kleisauke** [comment]
... I'm currently A/B testing commit https://github.com/kleisauke/libvips/commit/164e5010cd9e1ef4e376a6f86341e38602fae4a4 in production. Seems to work so far, I'll open a PR for that shortly.

**Comment by jcupitt** [comment]
Ah nice!

Here's a silly benchmark for that arrayjoin change. This program shrinks 5 images down to 16x9 pixels, then assembles 14,000 of them in a grid to make a 1920x1080 pixel image:

```python
#!/usr/bin/python3

import pyvips

WIDTH = 1920
HEIGHT = 1080
parts = 120

small_x = int (WIDTH/parts)
small_y = int (HEIGHT/parts)

images = [pyvips.Image
            .thumbnail(f"{i}.png", small_x, height=small_y, size="force")
            .copy_memory()
          for i in range(1, 6)]
        
tojoin = [images[i % 5] for i in range(parts ** 2)]

final = pyvips.Image.arrayjoin(tojoin, across=parts)
print(f"writing {final} to final.png ...")
final.write_to_file("final.png")
```

With libvips 8.13:

```
$ time ../join-vips.py 
writing <pyvips.Image 1920x1080 uchar, 3 bands, srgb> to final.png ...

real	2m16.933s
user	2m16.803s
sys	0m0.224s
```

And 8.14 with the arrayjoin fix:

```
$ time ../join-vips.py 
writing <pyvips.Image 1920x1080 uchar, 3 bands, srgb> to final.png ...

real	0m0.762s
user	0m1.032s
sys	0m0.365s
```

**Comment by kleisauke** [comment]
Windows binaries for libvips 8.14.0 are now available at https://github.com/libvips/build-win64-mxe/releases/tag/v8.14.0 (also marked as pre-release). :tada:

> I'm currently A/B testing commit [kleisauke@164e501](https://github.com/kleisauke/libvips/commit/164e5010cd9e1ef4e376a6f86341e38602fae4a4) in production. Seems to work so far, I'll open a PR for that shortly.

I just opened PR https://github.com/libvips/libvips/pull/3253 for this.

**Comment by jcupitt** [comment]
I got `vipsprofile` working again and tested [`vips-bench`](https://github.com/libvips/vips-bench) with 8.14. I see:

```
$ VIPS_CONCURRENCY=4 VIPS_PROFILE=1 time ./vips-c tmp/x.tif tmp/x2.tif
recording profile in vips-profile.txt
1.55user 0.32system 0:00.68elapsed 276%CPU (0avgtext+0avgdata 73444maxresident)k
0inputs+458352outputs (1major+13230minor)pagefaults 0swaps
$ vipsprofile 
reading from vips-profile.txt
loaded 49534 events
total time = 0.568802
name		alive	wait%	work%	unkn%	memory	peakm
     worker 6	  0.53	 28.9	62.3	8.89	 17.5	 17.5	
     worker 7	  0.54	 28.7	62.3	8.99	 2.87	 2.87	
     worker 8	  0.54	 24.9	64.8	10.3	 9.84	 9.84	
     worker 9	  0.53	 30.9	60.2	8.92	 6.23	 6.23	
   wbuffer 10	  0.54	 81	19	0.0116	 3.23	 3.23	
   wbuffer 11	  0.54	 73.7	26.3	0.0153	 0	 0	
peak memory = 39.6 MB
leak! final memory = 39.6 MB
gate overlap on thread wbuffer 10
overlap:
event wbuffer_write work starts at 0.038371 stops at 0.040458
event vips__region_take_ownership wait starts at 0.038409 stops at 0.03841
writing to vips-profile.svg
```

It's curious there's so much wait time for the four workers, I'll see if I can see a cause.

Graph:

![vips-profile](https://user-images.githubusercontent.com/580843/210600105-9a14c864-e560-4450-bb25-e9bfd52ac93e.svg)

**Comment by jcupitt** [comment]
Here's 8.12 on the same test:

```
$ vipsprofile 
reading from vips-profile.txt
loaded 39345 events
total time = 0.416592
name		alive	wait%	work%	unkn%	memory	peakm
    worker 12	  0.41	 6.38	85.6	7.97	 2.99	 2.99	
    worker 13	  0.41	 5.97	85.7	8.3	 2.52	 2.52	
    worker 14	  0.41	 6.75	85.1	8.15	 5.84	 5.84	
    worker 15	  0.41	 6.73	85	8.23	 2.61	 2.61	
   wbuffer 16	  0.41	 58.8	41.1	0.0193	 3.23	 3.23	
   wbuffer 17	  0.41	 69	31	0.014	 0	 0	
peak memory = 17.2 MB
leak! final memory = 17.2 MB
gate overlap on thread wbuffer 16
overlap:
event wbuffer_write work starts at 0.00964 stops at 0.037622
event vips__region_take_ownership wait starts at 0.009694 stops at 0.009696
writing to vips-profile.svg
```

Around 6% wait time.

**Comment by jcupitt** [comment]
I modified `vipsprofile` to output the top 10 worst waits:

```
name  wait
   vips__semaphore_downn_until	0.79
      vips_sequential_generate	0.52
         vips_worker_work_unit	0.00
           vips_line_cache_gen	0.00
           vips_tile_cache_gen	0.00
   vips__region_take_ownership	0.00
             vips__region_stop	0.00
           vips_region_dispose	0.00
             vips_region_build	0.00
            vips__region_start	0.00
```

So it's the extra lock that was added to `sequential`, sigh.

**Comment by jcupitt** [comment]
Ah, removing the `access="sequential"` from the benchmark fixes this, though it feels a bit cheaty.

**Comment by kleisauke** [comment]
> So it's the `vips_sequential()` in `reducev`, sigh.

Ah, which makes https://github.com/libvips/libvips/discussions/2757 relevant here. I'll look into that in the 8.15 release cycle. 

FWIW, I couldn't find an easy way to test with random access on CLI. `[access=random]` didn't help:
```console
$ vips reducev x.jpg[access=random] vips.jpg[strip] 1.5 --vips-info | grep "sequential"
VIPS-INFO: 11:37:16.980: reducev sequential line cache
```

> Ah, removing the `access="sequential"` from the benchmark fixes this

Just wondering, was the 8.11 benchmarks tested without  `access="sequential"`? I remembered the timings mentioned in comment https://github.com/libvips/libvips/issues/3067#issuecomment-1281969730.

**Comment by kmartinez** [comment]
ooof I forgot how much setup vips-bench needs (sorry for all the spam!) is there a simple way to test this @kleisauke ?

**Comment by kleisauke** [comment]
@kmartinez Here are some snippets I use for benchmarking:

<details>
  <summary>vips-bench</summary>

```bash
git clone https://github.com/libvips/vips-bench.git
cd vips-bench

mkdir -p tmp

# Build test image
vips colourspace sample2.v tmp/t1.v srgb
vips replicate tmp/t1.v tmp/t2.v 40 30
vips extract_area tmp/t2.v tmp/x.tif[tile] 0 0 10000 10000
vipsheader tmp/x.tif

# Compile libvips c benchmark
gcc -O3 vips.c `pkg-config vips --cflags --libs` -o vips-c

# Adjust concurrency, if needed
export VIPS_CONCURRENCY=16

# Debug, if needed
export VIPS_INFO=1
export VIPS_LEAK=1

# Benchmark
/usr/bin/time -f %M:%e ./vips-c tmp/x.tif tmp/x2.tif

# Test seq access
git revert --no-commit 0471ce44a1f0102f888eed10c79a6ce970efbf37

gcc -O3 vips.c `pkg-config vips --cflags --libs` -o vips-c

/usr/bin/time -f %M:%e ./vips-c tmp/x.tif tmp/x2.tif

git revert --abort
```
</details>

<details>
  <summary>simd-highway branch</summary>

```bash
# simd-highway branch depends on the RearrangeToOddPlusEven operation,
# which is not yet available in a released version of Highway.
git clone https://github.com/google/highway.git
cd highway

cmake -G Ninja -S . -B build \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DBUILD_SHARED_LIBS=ON \
  -DBUILD_TESTING=OFF \
  -DHWY_ENABLE_{CONTRIB,EXAMPLES}=OFF
cmake --build build -- -j$(nproc)
sudo cmake --install build

cd ../

git clone -b simd-highway https://github.com/kleisauke/libvips.git 
cd libvips

meson setup build \
  --prefix=/usr \
  --buildtype=release \
  -D{deprecated,examples,introspection}=false
meson compile -Cbuild
sudo meson install -Cbuild

vips --vips-config | grep highway
vips --targets

cd ../vips-bench

export VIPS_NOSIMD=1

/usr/bin/time -f %M:%e ./vips-c tmp/x.tif tmp/x2.tif

unset VIPS_NOSIMD

# ~HWY_SSSE3
export VIPS_SIMD="-4097"

/usr/bin/time -f %M:%e ./vips-c tmp/x.tif tmp/x2.tif

# ~HWY_SSE4
export VIPS_SIMD="-2049"

/usr/bin/time -f %M:%e ./vips-c tmp/x.tif tmp/x2.tif

# ~HWY_AVX2
export VIPS_SIMD="-513"

/usr/bin/time -f %M:%e ./vips-c tmp/x.tif tmp/x2.tif

# ~HWY_AVX3
export VIPS_SIMD="-257"

/usr/bin/time -f %M:%e ./vips-c tmp/x.tif tmp/x2.tif

unset VIPS_SIMD
```
</details>

**Comment by jcupitt** [comment]
> Just wondering, was the 8.11 benchmarks tested without access="sequential"? I remembered the timings mentioned in comment https://github.com/libvips/libvips/issues/3067#issuecomment-1281969730.

8.11 didn't have the seq in reducev (I think), so it didn't matter if sequential was on or not (I think!).

**Comment by kleisauke** [comment]
> 8.11 didn't have the seq in reducev (I think), so it didn't matter if sequential was on or not (I think!).

That seq was introduced in v8.5.1, so I found it a bit curious that it had no effect on v8.11.x (assuming that those benchmarks were run with `access="sequential"`).

FWIW, using commit https://github.com/kleisauke/libvips/commit/6438e35fc4d5441de6402da1951ffe612f6f8a95, I confirm that this performance regression is due to the `vips_sequential()` in `reducev` and `shrinkv`. Though, that commit is not considered safe, see e.g. comment https://github.com/libvips/libvips/discussions/2757#discussioncomment-2551070.

**Comment by kmartinez** [comment]
> @kmartinez Here are some snippets I use for benchmarking:
> vips-bench
> simd-highway branch

Thanks @kleisauke - I've also nearly got vips-bench running OK - I can commit a few minor mods (env ruby and nip2 default location)

**Comment by kmartinez** [comment]
here's your simd-highway on my 12 core zen4 PC:
100212:0.30
101688:0.30
100192:0.29
99044:0.32
98656:0.31

not sure what that means!

**Comment by kmartinez** [comment]
I committed the minor mods to .rb file headers and nip2 script - also added more packages needed to README

**Comment by kleisauke** [comment]
@kmartinez Thanks for testing that branch. What did these commands output?:
```
vips --vips-config | grep highway
vips --targets
```

The first command (i.e. the `VIPS_NOSIMD` env)  is testing the C path, so it should be somewhat slower than those subsequent commands (i.e. the `VIPS_SIMD` env, which enforces specific SIMD paths).

**Comment by kmartinez** [comment]
Hmm nothing and unknown option - I did install your vips - I'll check its not using some other version (its reporting 8-14.1)

**Comment by kmartinez** [comment]
Ah - I recompiled and installed - now I get
vips --vips-config | grep highway
vips: symbol lookup error: vips: undefined symbol: vips_simd_get_builtin_targets
some package dependency missing I guess!

**Comment by kleisauke** [comment]
Ah, I see. It was probably testing the liborc paths then (those environment variables do not affect 8.14.x).

A real time of 0.29 seconds on that benchmark is I think the fastest time I've ever noticed. :)

**Comment by kmartinez** [comment]
in theory it can run AVX-512 (but at half speed I think as it only has 256 bit units)

**Comment by kleisauke** [comment]
> vips: symbol lookup error: vips: undefined symbol: vips_simd_get_builtin_targets

Perhaps `sudo ldconfig`? Though, it could still conflict with another libvips installation.

I'm at https://gitter.im/libvips/devchat if you want me to help debug this.

> in theory it can run AVX-512 (but at half speed I think as it only has 256 bit units)

I think the `HWY_AVX3` path enables that, my CPU does not currently have support for that.

**Comment by jcupitt** [comment]
Any opinions on releasing 8.14.1? 

Does anyone know if the rpms are working well enough now?

**Comment by dloebl** [comment]
**I just wanted to give some feedback on libvips v8.14:**
We didn't notice any major issue when testing libvips v8.14 pre-release. Things are looking good on our side.
The only issue we noticed is that the EXIF support for PNG load and save caused some inconsistency compared to v8.13:
Some PNGs with an EXIF orientation tag started to flip/rotate with v8.14. I created a discussion for this (#3269).

**Comment by kleisauke** [comment]
I think it's safe to release 8.14.1, my concerns about the new threading system was addressed with PR #3253. AFAIK, the issues found in the RPM package were all fixed in the [`8.14`](https://github.com/libvips/libvips/tree/8.14) branch. Though, I'm not sure about the deb package (hopefully they will fix #2812 at some point too).

FWIW, the release notes and updated documentation in the https://github.com/libvips/libvips/compare/gh-pages...gh-pages-8.14 changeset looks good to me. 👍

**Comment by jcupitt** [comment]
OK, let's push the button then! Internet stand by ...

**Comment by jcupitt** [comment]
All done.

Thank you everyone, and goodnight!
